<?xml version="1.0"?>
<package format="3">
  <name>mycobot_vision</name>
  <version>0.1.0</version>

  <description>
    Physical dual-camera bringup and object detection for the
    myCobot 280 Jetson Nano.
  </description>

  <maintainer email="rajindulkar7@gmail.com">
    Raj Indulkar
  </maintainer>

  <license>BSD-2-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>image_proc</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>usb_cam</exec_depend>
  <exec_depend>vision_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>